languageCode = "ja-jp"
languageName = "Japanese(Japan)"
displayName = ":jp:"
isoCode = "ja-JP"
weight = 1
rtl = false

title = "kame404 blog"
logo = "img/kame404_logo.png"
description = "kame404 Blog"
copyright = "&copy; 2022 kame404"

dateFormat = "2006å¹´1æœˆ2æ—¥"

[author]
  name = "kame404"
  image = "img/kame404_logo.png"
  headline = "I'm a graphic designer who loves to create delicious 3D images"
  bio = "ã“ã‚“ã«ã¡ã¯ï¼ kame404 ã§ã™ğŸ¥° ã€Œè»½ã•ã€ã¨ã€Œç¾å‘³ã—ã•ã€ã‚’ä¸¡ç«‹ã—ãŸé£Ÿã¹ç‰©ã®CGã‚’ä½œã‚Šã¾ã™ã€‚"
  links = [
    { twitter = "https://twitter.com/kame404" },
    { github = "https://github.com/kame404" },
    { email = "mailto:404kame@gmail.com" },
  ]
